version: '3.8'

networks:
  cassandra-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24

services:
  cassandra-1:
    image: cassandra:latest
    container_name: cassandra-1
    hostname: cassandra-1
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RACK1
      - CASSANDRA_SEEDS=cassandra-1
      - JVM_EXTRA_OPTS=-Dcom.sun.management.jmxremote=true 
                        -Dcom.sun.management.jmxremote.port=7199
                        -Dcom.sun.management.jmxremote.rmi.port=7199
                        -Dcom.sun.management.jmxremote.ssl=false 
                        -Dcom.sun.management.jmxremote.authenticate=false 
                        -Djava.rmi.server.hostname=0.0.0.0
      - LOCAL_JMX=no
    networks:
      cassandra-net:
        ipv4_address: 192.168.100.2
    ports:
      - 7199:7199
      - 9042:9042
    restart: always


  cassandra-2:
    image: cassandra:latest
    container_name: cassandra-2
    hostname: cassandra-2
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RACK1
      - CASSANDRA_SEEDS=cassandra-1
      - JVM_EXTRA_OPTS=-Dcom.sun.management.jmxremote=true 
                        -Dcom.sun.management.jmxremote.port=7200
                        -Dcom.sun.management.jmxremote.rmi.port=7200
                        -Dcom.sun.management.jmxremote.ssl=false 
                        -Dcom.sun.management.jmxremote.authenticate=false 
                        -Djava.rmi.server.hostname=0.0.0.0
      - LOCAL_JMX=no
    networks:
      cassandra-net:
        ipv4_address: 192.168.100.3
    ports:
      - 7200:7200
      - 9043:9042
    depends_on:
      - cassandra-1
    restart: always

  cassandra-3:
    image: cassandra:latest
    container_name: cassandra-3
    hostname: cassandra-3
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RACK1
      - CASSANDRA_SEEDS=cassandra-1
      - JVM_EXTRA_OPTS=-Dcom.sun.management.jmxremote=true 
                        -Dcom.sun.management.jmxremote.port=7201
                        -Dcom.sun.management.jmxremote.rmi.port=7201
                        -Dcom.sun.management.jmxremote.ssl=false 
                        -Dcom.sun.management.jmxremote.authenticate=false 
                        -Djava.rmi.server.hostname=0.0.0.0
      - LOCAL_JMX=no
    networks:
      cassandra-net:
        ipv4_address: 192.168.100.4
    ports:
      - 7201:7201
      - 9044:9042
    depends_on:
      - cassandra-1
    restart: always
